### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mahesh-panchal** [mahesh-panchal/EBP-test-species#1]
## Manage Data:

- [ ] Delivery to `/data/deliveries`:
- [ ] PacBio WGS data linked in `/data/raw-data/PacBio-WGS`
- [ ] Hi-C data linked in `/data/raw-data/Illumina-HiC`
- [ ] RNAseq data linked in `/data/raw-data/Illumina-RNAseq`
- [ ] Project details updated into `README.md`

## Assembly:

- [ ] GenomeScope
- [ ] MashScreen
- [ ] Ploidyplot
- [ ] KAT GC
- [ ] Hifiasm
