### ISSUE TITLE
[Task List] Test species

### ISSUE THREAD

**Issue by mahesh-panchal** [mahesh-panchal/EBP-test-species#2]
## Manage Data:

- [ ] Project details updated into `README.md`.
- [ ] Delivery to `/data/deliveries`.
- [ ] PacBio WGS data linked in `/data/raw-data/PacBio-WGS`.
- [ ] Hi-C data linked in `/data/raw-data/Illumina-HiC`.
- [ ] RNAseq data linked in `/data/raw-data/Illumina-RNAseq`.

## Assembly:

- [ ] GenomeScope
- [ ] MashScreen
- [ ] Ploidyplot
- [ ] KAT GC
- [ ] Hifiasm
